// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "RL GitHub",
            "url": "https://github.com/rl-os/api"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v2/me/{mode}": {
            "get": {
                "security": [
                    {
                        "OAuth2": []
                    }
                ],
                "description": "get string by ID",
                "tags": [
                    "Current user"
                ],
                "summary": "Create new user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "game mod",
                        "name": "mode",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ResponseFormat"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "get string by ID",
                "summary": "Create new user",
                "parameters": [
                    {
                        "description": "JSON payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ResponseFormat"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Country": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "entity.Cover": {
            "type": "object",
            "properties": {
                "custom_url": {
                    "type": "object"
                },
                "id": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "entity.GradeCounts": {
            "type": "object",
            "properties": {
                "a": {
                    "type": "integer"
                },
                "s": {
                    "type": "integer"
                },
                "sh": {
                    "type": "integer"
                },
                "ss": {
                    "type": "integer"
                },
                "ssh": {
                    "type": "integer"
                }
            }
        },
        "entity.Kudosu": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "entity.Level": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "integer"
                },
                "progress": {
                    "type": "integer"
                }
            }
        },
        "entity.MonthlyPlaycounts": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "entity.Page": {
            "type": "object",
            "properties": {
                "html": {
                    "type": "string"
                },
                "raw": {
                    "type": "string"
                }
            }
        },
        "entity.Rank": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "integer"
                },
                "global": {
                    "type": "integer"
                }
            }
        },
        "entity.RankHistory": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "mode": {
                    "type": "string"
                }
            }
        },
        "entity.Statistics": {
            "type": "object",
            "properties": {
                "grade_counts": {
                    "type": "object",
                    "$ref": "#/definitions/entity.GradeCounts"
                },
                "hit_accuracy": {
                    "type": "number"
                },
                "is_ranked": {
                    "type": "boolean"
                },
                "level": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Level"
                },
                "maximum_combo": {
                    "type": "integer"
                },
                "play_count": {
                    "type": "integer"
                },
                "play_time": {
                    "type": "integer"
                },
                "pp": {
                    "type": "number"
                },
                "pp_rank": {
                    "type": "integer"
                },
                "rank": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Rank"
                },
                "ranked_score": {
                    "type": "integer"
                },
                "replays_watched_by_others": {
                    "type": "integer"
                },
                "total_hits": {
                    "type": "integer"
                },
                "total_score": {
                    "type": "integer"
                }
            }
        },
        "entity.User": {
            "type": "object",
            "properties": {
                "account_history": {
                    "description": "joins",
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "active_tournament_banner": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "avatar_url": {
                    "type": "string"
                },
                "badges": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "can_moderate": {
                    "type": "boolean"
                },
                "country": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Country"
                },
                "country_code": {
                    "type": "string"
                },
                "cover": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Cover"
                },
                "cover_url": {
                    "type": "string"
                },
                "default_group": {
                    "type": "string"
                },
                "discord": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "favourite_beatmapset_count": {
                    "type": "integer"
                },
                "follower_count": {
                    "type": "integer"
                },
                "graveyard_beatmapset_count": {
                    "type": "integer"
                },
                "has_supported": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "interests": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_bng": {
                    "type": "boolean"
                },
                "is_bot": {
                    "type": "boolean"
                },
                "is_full_bn": {
                    "type": "boolean"
                },
                "is_gmt": {
                    "description": "computed",
                    "type": "boolean"
                },
                "is_limited_bn": {
                    "type": "boolean"
                },
                "is_nat": {
                    "type": "boolean"
                },
                "is_online": {
                    "type": "boolean"
                },
                "is_supporter": {
                    "type": "boolean"
                },
                "join_date": {
                    "type": "string"
                },
                "kudosu": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Kudosu"
                },
                "last_visit": {
                    "type": "string"
                },
                "lastfm": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "loved_beatmapset_count": {
                    "type": "integer"
                },
                "max_blocks": {
                    "type": "integer"
                },
                "max_friends": {
                    "type": "integer"
                },
                "monthly_playcounts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.MonthlyPlaycounts"
                    }
                },
                "occupation": {
                    "type": "string"
                },
                "page": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Page"
                },
                "playmode": {
                    "type": "string"
                },
                "playstyle": {
                    "type": "string"
                },
                "pm_friends_only": {
                    "type": "boolean"
                },
                "post_count": {
                    "type": "integer"
                },
                "previous_usernames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "profile_colour": {
                    "type": "object"
                },
                "profile_order": {
                    "type": "string"
                },
                "rankHistory": {
                    "type": "object",
                    "$ref": "#/definitions/entity.RankHistory"
                },
                "ranked_and_approved_beatmapset_count": {
                    "type": "integer"
                },
                "replays_watched_counts": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "scores_first_count": {
                    "type": "integer"
                },
                "skype": {
                    "type": "string"
                },
                "statistics": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Statistics"
                },
                "support_level": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "twitter": {
                    "type": "string"
                },
                "unranked_beatmapset_count": {
                    "type": "integer"
                },
                "user_achievements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.UserAchievements"
                    }
                },
                "username": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "entity.UserAchievements": {
            "type": "object",
            "properties": {
                "achieved_at": {
                    "type": "string"
                },
                "achievement_id": {
                    "type": "integer"
                }
            }
        },
        "errors.ResponseFormat": {
            "type": "object",
            "properties": {
                "error_description": {
                    "type": "string"
                },
                "error_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "request.CreateUser": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "OAuth2": {
            "type": "oauth2",
            "flow": "password",
            "tokenUrl": "/oauth/token",
            "scopes": {
                "*": " Grants all access"
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "2.0",
	Host:        "localhost:2400",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "osu!lazer API",
	Description: "This is a simple server.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
