// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "RL GitHub",
            "url": "https://github.com/rl-os/api"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v2/beatmaps/lookup": {
            "get": {
                "tags": [
                    "Beatmap"
                ],
                "summary": "Lookup beatmap by id, checksum, filename",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "beatmap id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "beatmap file md5",
                        "name": "checksum",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "beatmap filename (legacy)",
                        "name": "filename",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.SingleBeatmap"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ResponseFormat"
                        }
                    }
                }
            }
        },
        "/api/v2/beatmaps/{id}": {
            "get": {
                "tags": [
                    "Beatmap"
                ],
                "summary": "Return beatmap by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "beatmap id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.SingleBeatmap"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ResponseFormat"
                        }
                    }
                }
            }
        },
        "/api/v2/beatmaps/{id}/scores": {
            "get": {
                "tags": [
                    "Beatmap"
                ],
                "summary": "Scores submitted to selected beatmap",
                "parameters": [
                    {
                        "type": "string",
                        "description": "beatmap id",
                        "name": "beatmap",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "score type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "osu! game mode (std, mania, ctb and etc)",
                        "name": "mode",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.SingleBeatmap"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ResponseFormat"
                        }
                    }
                }
            }
        },
        "/api/v2/beatmapsets/lookup": {
            "get": {
                "tags": [
                    "Beatmapset"
                ],
                "summary": "Lookup beatmapset by beatmap id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "beatmap id",
                        "name": "beatmap_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.BeatmapSetFull"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ResponseFormat"
                        }
                    }
                }
            }
        },
        "/api/v2/beatmapsets/search": {
            "get": {
                "tags": [
                    "Beatmapset"
                ],
                "summary": "Search Beatmapset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "query",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "mode",
                        "name": "m",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "status",
                        "name": "s",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "genre",
                        "name": "g",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "lang",
                        "name": "l",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.BeatmapsetSearchResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ResponseFormat"
                        }
                    }
                }
            }
        },
        "/api/v2/beatmapsets/{id}": {
            "get": {
                "tags": [
                    "Beatmapset"
                ],
                "summary": "Get beatmap by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "beatmapset id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.BeatmapSetFull"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ResponseFormat"
                        }
                    }
                }
            }
        },
        "/api/v2/beatmapsets/{id}/favourites": {
            "post": {
                "security": [
                    {
                        "OAuth2": []
                    }
                ],
                "tags": [
                    "Beatmapset"
                ],
                "summary": "Favourite beatmapset",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "beatmapset id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "favourite",
                            "unfavourite"
                        ],
                        "type": "string",
                        "description": "action",
                        "name": "action",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ResponseFormat"
                        }
                    }
                }
            }
        },
        "/api/v2/me/{mode}": {
            "get": {
                "security": [
                    {
                        "OAuth2": []
                    }
                ],
                "tags": [
                    "Current user"
                ],
                "summary": "Return current user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "game mod",
                        "name": "mode",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ResponseFormat"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "get string by ID",
                "summary": "Create new user",
                "parameters": [
                    {
                        "description": "JSON payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ResponseFormat"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Availability": {
            "type": "object",
            "properties": {
                "download_disabled": {
                    "type": "boolean"
                },
                "more_information": {
                    "type": "object"
                }
            }
        },
        "entity.Beatmap": {
            "type": "object",
            "properties": {
                "accuracy": {
                    "type": "integer"
                },
                "ar": {
                    "type": "integer"
                },
                "beatmapset_id": {
                    "type": "integer"
                },
                "bpm": {
                    "type": "integer"
                },
                "convert": {
                    "type": "boolean"
                },
                "count_circles": {
                    "type": "integer"
                },
                "count_sliders": {
                    "type": "integer"
                },
                "count_spinners": {
                    "type": "integer"
                },
                "count_total": {
                    "type": "integer"
                },
                "cs": {
                    "type": "integer"
                },
                "deleted_at": {
                    "type": "string"
                },
                "difficulty_rating": {
                    "type": "number"
                },
                "drain": {
                    "type": "integer"
                },
                "failtimes": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Failtimes"
                },
                "hit_length": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_scoreable": {
                    "type": "boolean"
                },
                "last_updated": {
                    "type": "string"
                },
                "max_combo": {
                    "type": "integer"
                },
                "mode": {
                    "type": "string"
                },
                "mode_int": {
                    "type": "integer"
                },
                "passcount": {
                    "type": "integer"
                },
                "playcount": {
                    "type": "integer"
                },
                "ranked": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "total_length": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "entity.BeatmapSet": {
            "type": "object",
            "properties": {
                "artist": {
                    "type": "string"
                },
                "availability": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Availability"
                },
                "bpm": {
                    "type": "integer"
                },
                "can_be_hyped": {
                    "type": "boolean"
                },
                "covers": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Covers"
                },
                "creator": {
                    "type": "string"
                },
                "description": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Description"
                },
                "discussion_enabled": {
                    "type": "boolean"
                },
                "discussion_locked": {
                    "type": "boolean"
                },
                "favourite_count": {
                    "type": "integer"
                },
                "genre": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Genre"
                },
                "has_favourited": {
                    "type": "boolean"
                },
                "hype": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Hype"
                },
                "id": {
                    "type": "integer"
                },
                "is_scoreable": {
                    "type": "boolean"
                },
                "language": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Genre"
                },
                "last_checked": {
                    "type": "string"
                },
                "last_updated": {
                    "type": "string"
                },
                "legacy_thread_url": {
                    "type": "string"
                },
                "nominations": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Hype"
                },
                "play_count": {
                    "type": "integer"
                },
                "preview_url": {
                    "type": "string"
                },
                "ranked": {
                    "type": "integer"
                },
                "ranked_date": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "storyboard": {
                    "type": "boolean"
                },
                "submitted_date": {
                    "type": "string"
                },
                "tags": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "user": {
                    "type": "object",
                    "$ref": "#/definitions/entity.UserShortField"
                },
                "user_id": {
                    "type": "integer"
                },
                "video": {
                    "type": "boolean"
                }
            }
        },
        "entity.BeatmapSetFull": {
            "type": "object",
            "properties": {
                "artist": {
                    "type": "string"
                },
                "availability": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Availability"
                },
                "beatmaps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Beatmap"
                    }
                },
                "bpm": {
                    "type": "integer"
                },
                "can_be_hyped": {
                    "type": "boolean"
                },
                "converts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Beatmap"
                    }
                },
                "covers": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Covers"
                },
                "creator": {
                    "type": "string"
                },
                "current_user_attributes": {
                    "type": "object",
                    "$ref": "#/definitions/entity.CurrentUserAttributes"
                },
                "description": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Description"
                },
                "discussion_enabled": {
                    "type": "boolean"
                },
                "discussion_locked": {
                    "type": "boolean"
                },
                "favourite_count": {
                    "type": "integer"
                },
                "genre": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Genre"
                },
                "has_favourited": {
                    "type": "boolean"
                },
                "hype": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Hype"
                },
                "id": {
                    "type": "integer"
                },
                "is_scoreable": {
                    "type": "boolean"
                },
                "language": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Genre"
                },
                "last_checked": {
                    "type": "string"
                },
                "last_updated": {
                    "type": "string"
                },
                "legacy_thread_url": {
                    "type": "string"
                },
                "nominations": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Hype"
                },
                "play_count": {
                    "type": "integer"
                },
                "preview_url": {
                    "type": "string"
                },
                "ranked": {
                    "type": "integer"
                },
                "ranked_date": {
                    "type": "string"
                },
                "ratings": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "recent_favourites": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.UserShortField"
                    }
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "storyboard": {
                    "type": "boolean"
                },
                "submitted_date": {
                    "type": "string"
                },
                "tags": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "user": {
                    "type": "object",
                    "$ref": "#/definitions/entity.UserShortField"
                },
                "user_id": {
                    "type": "integer"
                },
                "video": {
                    "type": "boolean"
                }
            }
        },
        "entity.BeatmapsetSearch": {
            "type": "object",
            "properties": {
                "artist": {
                    "type": "string"
                },
                "availability": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Availability"
                },
                "beatmaps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Beatmap"
                    }
                },
                "bpm": {
                    "type": "integer"
                },
                "can_be_hyped": {
                    "type": "boolean"
                },
                "covers": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Covers"
                },
                "creator": {
                    "type": "string"
                },
                "discussion_enabled": {
                    "type": "boolean"
                },
                "discussion_locked": {
                    "type": "boolean"
                },
                "favourite_count": {
                    "type": "integer"
                },
                "has_favourited": {
                    "type": "boolean"
                },
                "hype": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Hype"
                },
                "id": {
                    "type": "integer"
                },
                "is_scoreable": {
                    "type": "boolean"
                },
                "last_updated": {
                    "type": "string"
                },
                "legacy_thread_url": {
                    "type": "string"
                },
                "nominations": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Nominations"
                },
                "play_count": {
                    "type": "integer"
                },
                "preview_url": {
                    "type": "string"
                },
                "ranked": {
                    "type": "integer"
                },
                "ranked_date": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "storyboard": {
                    "type": "boolean"
                },
                "submitted_date": {
                    "type": "string"
                },
                "tags": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "video": {
                    "type": "boolean"
                }
            }
        },
        "entity.BeatmapsetSearchResult": {
            "type": "object",
            "properties": {
                "beatmapsets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.BeatmapsetSearch"
                    }
                },
                "error": {
                    "type": "error"
                },
                "recommended_difficulty": {
                    "type": "number"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "entity.Country": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "entity.Cover": {
            "type": "object",
            "properties": {
                "custom_url": {
                    "type": "object"
                },
                "id": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "entity.Covers": {
            "type": "object",
            "properties": {
                "card": {
                    "type": "string"
                },
                "card@2x": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "cover@2x": {
                    "type": "string"
                },
                "list": {
                    "type": "string"
                },
                "list@2x": {
                    "type": "string"
                },
                "slimcover": {
                    "type": "string"
                },
                "slimcover@2x": {
                    "type": "string"
                }
            }
        },
        "entity.CurrentUserAttributes": {
            "type": "object",
            "properties": {
                "can_delete": {
                    "type": "boolean"
                },
                "can_hype": {
                    "type": "boolean"
                },
                "can_hype_reason": {
                    "type": "object"
                },
                "can_love": {
                    "type": "boolean"
                },
                "is_watching": {
                    "type": "boolean"
                },
                "new_hype_time": {
                    "type": "object"
                },
                "remaining_hype": {
                    "type": "integer"
                }
            }
        },
        "entity.Description": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                }
            }
        },
        "entity.Failtimes": {
            "type": "object",
            "properties": {
                "exit": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "fail": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "entity.Genre": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "entity.GradeCounts": {
            "type": "object",
            "properties": {
                "a": {
                    "type": "integer"
                },
                "s": {
                    "type": "integer"
                },
                "sh": {
                    "type": "integer"
                },
                "ss": {
                    "type": "integer"
                },
                "ssh": {
                    "type": "integer"
                }
            }
        },
        "entity.Hype": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "integer"
                },
                "required": {
                    "type": "integer"
                }
            }
        },
        "entity.Kudosu": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "entity.Level": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "integer"
                },
                "progress": {
                    "type": "integer"
                }
            }
        },
        "entity.MonthlyPlaycounts": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "entity.Nominations": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "integer"
                },
                "required": {
                    "type": "integer"
                }
            }
        },
        "entity.Page": {
            "type": "object",
            "properties": {
                "html": {
                    "type": "string"
                },
                "raw": {
                    "type": "string"
                }
            }
        },
        "entity.Rank": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "integer"
                },
                "global": {
                    "type": "integer"
                }
            }
        },
        "entity.RankHistory": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "mode": {
                    "type": "string"
                }
            }
        },
        "entity.SingleBeatmap": {
            "type": "object",
            "properties": {
                "accuracy": {
                    "type": "integer"
                },
                "ar": {
                    "type": "integer"
                },
                "beatmapset": {
                    "type": "object",
                    "$ref": "#/definitions/entity.BeatmapSet"
                },
                "beatmapset_id": {
                    "type": "integer"
                },
                "bpm": {
                    "type": "integer"
                },
                "convert": {
                    "type": "boolean"
                },
                "count_circles": {
                    "type": "integer"
                },
                "count_sliders": {
                    "type": "integer"
                },
                "count_spinners": {
                    "type": "integer"
                },
                "count_total": {
                    "type": "integer"
                },
                "cs": {
                    "type": "integer"
                },
                "deleted_at": {
                    "type": "string"
                },
                "difficulty_rating": {
                    "type": "number"
                },
                "drain": {
                    "type": "integer"
                },
                "failtimes": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Failtimes"
                },
                "hit_length": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_scoreable": {
                    "type": "boolean"
                },
                "last_updated": {
                    "type": "string"
                },
                "max_combo": {
                    "type": "integer"
                },
                "mode": {
                    "type": "string"
                },
                "mode_int": {
                    "type": "integer"
                },
                "passcount": {
                    "type": "integer"
                },
                "playcount": {
                    "type": "integer"
                },
                "ranked": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "total_length": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "entity.Statistics": {
            "type": "object",
            "properties": {
                "grade_counts": {
                    "type": "object",
                    "$ref": "#/definitions/entity.GradeCounts"
                },
                "hit_accuracy": {
                    "type": "number"
                },
                "is_ranked": {
                    "type": "boolean"
                },
                "level": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Level"
                },
                "maximum_combo": {
                    "type": "integer"
                },
                "play_count": {
                    "type": "integer"
                },
                "play_time": {
                    "type": "integer"
                },
                "pp": {
                    "type": "number"
                },
                "pp_rank": {
                    "type": "integer"
                },
                "rank": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Rank"
                },
                "ranked_score": {
                    "type": "integer"
                },
                "replays_watched_by_others": {
                    "type": "integer"
                },
                "total_hits": {
                    "type": "integer"
                },
                "total_score": {
                    "type": "integer"
                }
            }
        },
        "entity.User": {
            "type": "object",
            "properties": {
                "account_history": {
                    "description": "joins",
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "active_tournament_banner": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "avatar_url": {
                    "type": "string"
                },
                "badges": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "can_moderate": {
                    "type": "boolean"
                },
                "country": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Country"
                },
                "country_code": {
                    "type": "string"
                },
                "cover": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Cover"
                },
                "cover_url": {
                    "type": "string"
                },
                "default_group": {
                    "type": "string"
                },
                "discord": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "favourite_beatmapset_count": {
                    "type": "integer"
                },
                "follower_count": {
                    "type": "integer"
                },
                "graveyard_beatmapset_count": {
                    "type": "integer"
                },
                "has_supported": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "interests": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_bng": {
                    "type": "boolean"
                },
                "is_bot": {
                    "type": "boolean"
                },
                "is_full_bn": {
                    "type": "boolean"
                },
                "is_gmt": {
                    "description": "computed",
                    "type": "boolean"
                },
                "is_limited_bn": {
                    "type": "boolean"
                },
                "is_nat": {
                    "type": "boolean"
                },
                "is_online": {
                    "type": "boolean"
                },
                "is_supporter": {
                    "type": "boolean"
                },
                "join_date": {
                    "type": "string"
                },
                "kudosu": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Kudosu"
                },
                "last_visit": {
                    "type": "string"
                },
                "lastfm": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "loved_beatmapset_count": {
                    "type": "integer"
                },
                "max_blocks": {
                    "type": "integer"
                },
                "max_friends": {
                    "type": "integer"
                },
                "monthly_playcounts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.MonthlyPlaycounts"
                    }
                },
                "occupation": {
                    "type": "string"
                },
                "page": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Page"
                },
                "playmode": {
                    "type": "string"
                },
                "playstyle": {
                    "type": "string"
                },
                "pm_friends_only": {
                    "type": "boolean"
                },
                "post_count": {
                    "type": "integer"
                },
                "previous_usernames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "profile_colour": {
                    "type": "object"
                },
                "profile_order": {
                    "type": "string"
                },
                "rankHistory": {
                    "type": "object",
                    "$ref": "#/definitions/entity.RankHistory"
                },
                "ranked_and_approved_beatmapset_count": {
                    "type": "integer"
                },
                "replays_watched_counts": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "scores_first_count": {
                    "type": "integer"
                },
                "skype": {
                    "type": "string"
                },
                "statistics": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Statistics"
                },
                "support_level": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "twitter": {
                    "type": "string"
                },
                "unranked_beatmapset_count": {
                    "type": "integer"
                },
                "user_achievements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.UserAchievements"
                    }
                },
                "username": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "entity.UserAchievements": {
            "type": "object",
            "properties": {
                "achieved_at": {
                    "type": "string"
                },
                "achievement_id": {
                    "type": "integer"
                }
            }
        },
        "entity.UserShort": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "country_code": {
                    "type": "string"
                },
                "default_group": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "has_supported": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_bot": {
                    "type": "boolean"
                },
                "is_online": {
                    "type": "boolean"
                },
                "is_supporter": {
                    "type": "boolean"
                },
                "join_date": {
                    "type": "string"
                },
                "last_visit": {
                    "type": "string"
                },
                "pm_friends_only": {
                    "type": "boolean"
                },
                "support_level": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "entity.UserShortField": {
            "$ref": "#/definitions/entity.UserShort"
        },
        "errors.ResponseFormat": {
            "type": "object",
            "properties": {
                "error_description": {
                    "type": "string"
                },
                "error_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "request.CreateUser": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "OAuth2": {
            "type": "oauth2",
            "flow": "password",
            "tokenUrl": "/oauth/token",
            "scopes": {
                "*": " Grants all access"
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "2.0",
	Host:        "localhost:2400",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "osu!lazer API",
	Description: "This is a simple server.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
